---
- name: Test Windows Ansible Task
  hosts: windows
  tasks:
    - name: Check WinRM connectivity
      win_ping:

    - name: Get my user info
      ansible.windows.win_whoami:
      register: whoami_result
    
    - name: Display user information
      debug:
        var: whoami_result

    - name: Get system information
      win_shell: systeminfo
      register: systeminfo

    - name: Display system information
      debug:
        var: systeminfo.stdout_lines
